name: lafyu
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  badges: ^2.0.2
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  flutter_svg: ^1.0.3
  dropdown_button2: ^1.1.1
  dotted_border: ^2.0.0+2
  http: ^0.13.4
  shared_preferences: ^2.0.7
  rxdart: ^0.27.3
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/icons/
    - assets/images/
    - assets/menu/

